### ISSUE TITLE
Production mod

### ISSUE THREAD

**Issue by TheSkyFather** [What42Pizza/BudgetTracker#1]
Hi, I've been playing with your mindustry modification for a long time(production mod). And recently faced with the problem that it is not transferred to version 6.0, can you somehow contact you to discuss the question of I moved your modification to version 6.0? I'll do it myself, and you won't be required to do anything but give permission. Can you give your VK, Facebook or Gmail so I can contact you?

**Comment by What42Pizza** [comment]
The best way to contact me is through discord (my account is What42Pizza#0283). You're free to update Production Mod to V6 if you want, and if you do then could I put a link on the mod's page to your updated version?
